name = "book-echo-douban-proxy"
main = "worker/index.ts"
compatibility_date = "2026-03-28"
routes = [
  { pattern = "opus.thoamsy.me", custom_domain = true }
]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true

[[kv_namespaces]]
binding = "DOUBAN_CACHE"
id = "66bffc3bfb5843b3a1c7486ff97f795d"
